Philips.CodeAnalysis.MsTestAnalyzers/AssertIsTrueLiteralAnalyzer.cs

updated mstest analyzer - set enablebydefault to true

updated mstest analyzer - set enablebydefault to true

---

Philips.CodeAnalysis.MsTestAnalyzers/TestMethodsMustBeInTestClassAnalyzer.cs
Philips.CodeAnalysis.Test/TestMethodsMustBeInTestClassAnalyzerTest.cs

Fix corner case - not require TestClass attribute on abstract classes

TestClass attribute on abstract classes

---

Philips.CodeAnalysis.Common/DiagnosticIds.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/EnforceEditorConfigAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Philips.CodeAnalysis.MaintainabilityAnalyzers.csproj

added EnforceEditorConfigAnalyzer

added EnforceEditorConfigAnalyzer

---

Philips.CodeAnalysis.Common/AdditionalFilesHelper.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/AvoidStaticClassesAnalyzer.cs
Philips.CodeAnalysis.MsTestAnalyzers/TestHasCategoryAnalyzer.cs
Philips.CodeAnalysis.MsTestAnalyzers/TestMethodDiagnosticAnalyzer.cs
Philips.CodeAnalysis.Test/TestHasCategoryTest.cs

Moved hardcoded test categories to EditorConfig file

Made TestHasCategory analyzer generic

---

Philips.CodeAnalysis.Common/ConstructorSyntaxHelper.cs
Philips.CodeAnalysis.DuplicateCodeAnalyzer/Philips.CodeAnalysis.DuplicateCodeAnalyzer.csproj
Philips.CodeAnalysis.MaintainabilityAnalyzers/Philips.CodeAnalysis.MaintainabilityAnalyzers.csproj
Philips.CodeAnalysis.MaintainabilityAnalyzers/Philips.CodeAnalysis.MaintainabilityAnalyzers.md
Philips.CodeAnalysis.MaintainabilityAnalyzers/ServiceContractAreAnnotatedWithOperationContractAttributeAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/WinFormsInitializeComponentMustBeCalledOnceAnalyzer.cs
Philips.CodeAnalysis.MoqAnalyzers/Philips.CodeAnalysis.MoqAnalyzers.csproj
Philips.CodeAnalysis.MsTestAnalyzers/Philips.CodeAnalysis.MsTestAnalyzers.csproj
Philips.CodeAnalysis.Test/ServiceContractAreAnnotatedWithOperationContractAttributeAnalyzerTest.cs
Philips.CodeAnalysis.Test/WinFormsInitializeComponentMustBeCalledOnceAnalyzerTest.cs

Migrate a couple more analyzers

---

Philips.CodeAnalysis.MsTestAnalyzers/Philips.CodeAnalysis.MsTestAnalyzers.csproj

Increment revision

---

Philips.CodeAnalysis.Common/Helper.cs
Philips.CodeAnalysis.Common/MsTestFrameworkDefinitions.cs
Philips.CodeAnalysis.MsTestAnalyzers/DataTestMethodsHaveDataRowsAnalyzer.cs
Philips.CodeAnalysis.MsTestAnalyzers/Philips.CodeAnalysis.MsTestAnalyzers.csproj
Philips.CodeAnalysis.MsTestAnalyzers/TestMethodsMustHaveTheCorrectNumberOfArgumentsAnalyzer.cs
Philips.CodeAnalysis.Test/DataTestMethodsHaveDataRowsAnalyzerTest.cs
Philips.CodeAnalysis.Test/TestMethodsMustHaveTheCorrectNumberOfArgumentsAnalyzerTest.cs

This adds support for a variant of DataTestMethod.
https://www.meziantou.net/mstest-v2-data-tests.htm

Support DynamicDataAttribute

---

Philips.CodeAnalysis.MsTestAnalyzers/Philips.CodeAnalysis.MsTestAnalyzers.csproj
Philips.CodeAnalysis.MsTestAnalyzers/TestContextAnalyzer.cs

TestContext analyzer shouldn't be checking generated code

---

Philips.CodeAnalysis.Common/AdditionalFilesHelper.cs
Philips.CodeAnalysis.MsTestAnalyzers/TestHasCategoryAnalyzer.cs
Philips.CodeAnalysis.MsTestAnalyzers/TestMethodDiagnosticAnalyzer.cs

Loading the exceptions file and the allowed categories for every test is expensive
Closes #38

Preload the exceptions list and the allowed test categories

---

Philips.CodeAnalysis.MaintainabilityAnalyzers/Philips.CodeAnalysis.MaintainabilityAnalyzers.csproj
Philips.CodeAnalysis.MaintainabilityAnalyzers/ProhibitDynamicKeywordAnalyzer.cs
Philips.CodeAnalysis.Test/ProhibitDynamicKeywordAnalyzerTest.cs

Dynamic Keyword Bug Fix

---

Philips.CodeAnalysis.MaintainabilityAnalyzers/Philips.CodeAnalysis.MaintainabilityAnalyzers.csproj
Philips.CodeAnalysis.MaintainabilityAnalyzers/Philips.CodeAnalysis.MaintainabilityAnalyzers.md
Philips.CodeAnalysis.MaintainabilityAnalyzers/PositiveNamingAnalyzer.cs

Improved the description of the PositveNamingAnalyzer to correctly reflect its scope. This should give clear feedback for scenarios like issue #74.

Improve PositiveNaming description

---

Philips.CodeAnalysis.Common/DiagnosticIds.cs
Philips.CodeAnalysis.Common/Helper.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/AvoidAssignmentInConditionAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/LimitPathLengthAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/NoSpaceInFilenameAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Philips.CodeAnalysis.MaintainabilityAnalyzers.csproj
Philips.CodeAnalysis.MaintainabilityAnalyzers/Philips.CodeAnalysis.MaintainabilityAnalyzers.md
Philips.CodeAnalysis.Test/AvoidAssignmentInConditionAnalyzerTest.cs
Philips.CodeAnalysis.Test/LimitPathLengthAnalyzerTest.cs
Philips.CodeAnalysis.Test/NoSpaceInFilenameAnalyzerTest.cs

Add AvoidAssignmentInCondition, NoSpaceInFile and LimitPathLength Analyzers and tests.
No changes are required for these.

Add 3 Analyzers unchanged

---

Philips.CodeAnalysis.DuplicateCodeAnalyzer/AvoidDuplicateCodeAnalyzer.cs
Philips.CodeAnalysis.DuplicateCodeAnalyzer/Philips.CodeAnalysis.DuplicateCodeAnalyzer.csproj

Also, increase max token_count to 200.

Report character number as well as line number.

---

Philips.CodeAnalysis.DuplicateCodeAnalyzer/AvoidDuplicateCodeAnalyzer.cs
Philips.CodeAnalysis.DuplicateCodeAnalyzer/Philips.CodeAnalysis.DuplicateCodeAnalyzer.csproj

Temporary code to log source of NullReferenceException

Log stack info on exception

---

Philips.CodeAnalysis.Test/Maintainability/Maintainability/NoNestedStringFormatsAnalyzerTest.cs

Added some explicit test cases for #134 
On latest master I was unable to reproduce the actual issue, that's why there is no update to the production code.
Consider #134 solved.

Add explicit test cases for #134

---

.editorconfig
Philips.CodeAnalysis.Benchmark/Philips.CodeAnalysis.Benchmark.csproj
Philips.CodeAnalysis.Benchmark/Program.cs
Philips.CodeAnalysis.Test/DuplicateCode/AvoidDuplicateCodeTest.cs
Philips.CodeAnalysis.Test/Helpers/DiagnosticResult.cs
Philips.CodeAnalysis.Test/Maintainability/Maintainability/AvoidStaticClassAnalyzerTest.cs
Philips.CodeAnalysis.Test/Maintainability/Maintainability/EnforceFileVersionIsSameAsPackageVersionAnalyzerTest.cs
Philips.CodeAnalysis.Test/Maintainability/Maintainability/NoRegionsInMethodAnalyzerTest.cs
Philips.CodeAnalysis.Test/Maintainability/Maintainability/WinFormsInitializeComponentMustBeCalledOnceAnalyzerTest.cs
Philips.CodeAnalysis.Test/Maintainability/Naming/NamespacePrefixAnalyzerTest.cs
Philips.CodeAnalysis.Test/Maintainability/Naming/PositiveNamingAnalyzerTest.cs
Philips.CodeAnalysis.Test/Maintainability/Readability/AvoidInlineNewAnalyzerTest.cs
Philips.CodeAnalysis.Test/Maintainability/Readability/PreventUnnecessaryRangeChecksAnalyzerTest.cs
Philips.CodeAnalysis.Test/MsTest/AvoidMsFakesAnalyzerTest.cs
Philips.CodeAnalysis.Test/Philips.CodeAnalysis.Test.csproj
Philips.CodeAnalysis.Test/Verifiers/DiagnosticVerifier.cs

...and resulting IntelliSense findings

Net 3.1->Net7 (for Tests)

---

Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/AlignOperatorsCountAnalyzer.cs
Philips.CodeAnalysis.Test/Maintainability/Maintainability/AlignOperatorsCountAnalyzerTest.cs

Structs might even be more common to have operators.

fix: Count operators on structs also

---

Philips.CodeAnalysis.Common/ConstructorSyntaxHelper.cs
Philips.CodeAnalysis.Common/Helper.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/AvoidInvocationAsArgumentCodeFixProvider.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/AvoidPrivateKeyPropertyAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/AvoidStaticClassesAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/AvoidStaticMethodAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/AvoidTaskResultCodeFixProvider.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/AvoidThreadSleepAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/EnforceEditorConfigAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/EnforceFileVersionIsSameAsPackageVersionAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/LockObjectsMustBeReadonlyAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/NoHardCodedPathsAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/NoNestedStringFormatsAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/NoProtectedFieldsAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/NoRegionsInMethodAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/WinFormsInitializeComponentMustBeCalledOnceAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Naming/EnforceBoolNamingConventionAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Naming/NamespacePrefixAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Readability/PreventUnnecessaryRangeChecksCodeFixProvider.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/RuntimeFailure/DereferenceNullAnalyzer.cs
Philips.CodeAnalysis.MsTestAnalyzers/AssertFailAnalyzer.cs
Philips.CodeAnalysis.MsTestAnalyzers/DataTestMethodsHaveDataRowsAnalyzer.cs
Philips.CodeAnalysis.MsTestAnalyzers/TestHasCategoryAnalyzer.cs
Philips.CodeAnalysis.MsTestAnalyzers/TestHasTimeoutAnalyzer.cs

refactor: merge if statements 

---

Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/AvoidStaticMethodCodeFixProvider.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/CallExtensionMethodsAsInstanceMethodsAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Readability/LimitConditionComplexityAnalyzer.cs
Philips.CodeAnalysis.Test/Maintainability/Maintainability/AvoidStaticMethodAnalyzerTest.cs

Applied the findings from recently created Analyzer.

refactor: Apply Simplify LINQ

---

Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/AvoidArrayListAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/AvoidArrayListCodeFixProvider.cs
Philips.CodeAnalysis.Test/Maintainability/Maintainability/AvoidArrayListAnalyzerTest.cs

Implements #222, which names a few improvements on the `AvoidArrayListAnalyzer`

fix: Implement improvements on AvoidArrayListAnalyzer

---

Philips.CodeAnalysis.Common/DiagnosticIds.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/CastCompleteObjectAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Philips.CodeAnalysis.MaintainabilityAnalyzers.csproj
Philips.CodeAnalysis.MaintainabilityAnalyzers/Philips.CodeAnalysis.MaintainabilityAnalyzers.md
Philips.CodeAnalysis.Test/Maintainability/Maintainability/CastCompleteObjectAnalyzerTest.cs

The checks rule [10@404](https://tics.tiobe.com/viewerCS/?ID=131&CSTD=Rule) of the Philips C# Coding Standard.

feat: Introduce cast complete object Analyzer

---

Philips.CodeAnalysis.Common/DiagnosticIds.cs
Philips.CodeAnalysis.Common/Helper.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/PassSenderToEventHandlerAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/PassSenderToEventHandlerCodeFixProvider.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Philips.CodeAnalysis.MaintainabilityAnalyzers.csproj
Philips.CodeAnalysis.MaintainabilityAnalyzers/Philips.CodeAnalysis.MaintainabilityAnalyzers.md
Philips.CodeAnalysis.Test/Maintainability/Maintainability/PassSenderToEventHandlerAnalyzerTest.cs

This analyzer checks rule [9@112](https://tics.tiobe.com/viewerCS/?ID=2179&CSTD=Rule) of the Philips C# Coding Standard

feat: Introduce PassSenderToEventHandlerAnalyzer

---

Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/AvoidPrivateKeyPropertyAnalyzer.cs
Philips.CodeAnalysis.Test/Maintainability/Maintainability/AvoidPrivateKeyPropertyAnalyzerTest.cs

fix: bail out early

---

Philips.CodeAnalysis.Common/AdditionalFilesHelper.cs
Philips.CodeAnalysis.Common/AllowedSymbols.cs
Philips.CodeAnalysis.Common/AttributeDefinition.cs
Philips.CodeAnalysis.Common/ConstructorSyntaxHelper.cs
Philips.CodeAnalysis.Common/ExceptionsOptions.cs
Philips.CodeAnalysis.Common/Helper.cs
Philips.CodeAnalysis.Common/MsTestAttributeDefinition.cs
Philips.CodeAnalysis.Common/MsTestFrameworkDefinitions.cs
Philips.CodeAnalysis.Common/Philips.CodeAnalysis.Common.csproj
Philips.CodeAnalysis.Common/StaticClasses.Allowed.txt
Philips.CodeAnalysis.MaintainabilityAnalyzers/Documentation/DocumentThrownExceptionsAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Documentation/DocumentUnhandledExceptionsAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/WinFormsInitializeComponentMustBeCalledOnceAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Readability/SplitMultiLineConditionOnLogicalOperatorAnalyzer.cs
Philips.CodeAnalysis.MsTestAnalyzers/TestHasTimeoutAnalyzer.cs
Philips.CodeAnalysis.Test/Maintainability/Documentation/DocumentThrownExceptionsAnalyzerTest.cs
Philips.CodeAnalysis.Test/Maintainability/Readability/SplitMultiLineConditionOnLogicalOperatorAnalyzerTest.cs

Fixed a number of our own dogfood findings.

fix: Eat our own dogfood

---

Philips.CodeAnalysis.Common/Philips.CodeAnalysis.Common.csproj
Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/ReturnImmutableCollectionsAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/ReturnImmutableCollectionsCodeFixProvider.cs
Philips.CodeAnalysis.Test/Maintainability/Maintainability/ReturnImmutableCollectionsAnalyzerTest.cs

Implemented a code fixer that replaces the mutable type by their closest readonly interface.

fix: 285 code fixer for ph2129

---

Philips.CodeAnalysis.MaintainabilityAnalyzers/Documentation/DocumentUnhandledExceptionsAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/AvoidMagicNumbersAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/AvoidPragmaAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/AvoidTaskResultAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/NoNestedStringFormatsAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/ProhibitDynamicKeywordAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Naming/EnforceBoolNamingConventionAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Naming/VariableNamingConventionAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Readability/AvoidInlineNewAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Readability/AvoidMultipleLambdasOnSingleLineCodeFixProvider.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Readability/EnforceRegionsAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Readability/PreventUnnecessaryRangeChecksAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Readability/SplitMultiLineConditionOnLogicalOperatorAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/RegionVisitor.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/RuntimeFailure/DereferenceNullAnalyzer.cs

I have left the PH2128 violations in, as these are false positives according to #310
And 1 false positive on PH2028 which I wasn't able to resolve.

fix: MaintainabilityAnalyzers dogfood

---

Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/AvoidStaticClassesAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/AvoidStaticClassesCodeFixProvider.cs
Philips.CodeAnalysis.Test/Maintainability/Maintainability/AvoidStaticClassAnalyzerTest.cs

Add test to verify the fixer fixes the diagnostic.
This fixes #294

fix: Add test coverage

---

Philips.CodeAnalysis.MsTestAnalyzers/AvoidAttributeAnalyzer.cs
Philips.CodeAnalysis.Test/MsTest/AvoidAttributeAnalyzerTest.cs

The name was pretty well chosen actually, but anyway I fixed the dogfood by renaming it.

fix: renamed variable

---

Philips.CodeAnalysis.Common/TestHelper.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/AvoidMagicNumbersAnalyzer.cs
Philips.CodeAnalysis.Test/Maintainability/Maintainability/AvoidMagicNumbersAnalyzerTest.cs

To reduce the dogfood issues in out Test project

fix: disable magic numbers in test code

---

Philips.CodeAnalysis.Test/Maintainability/Documentation/CopyrightPresentAnalyzerTest.cs
Philips.CodeAnalysis.Test/Maintainability/Maintainability/AlignOperatorsCountAnalyzerTest.cs
Philips.CodeAnalysis.Test/Maintainability/Maintainability/AvoidArrayListAnalyzerTest.cs
Philips.CodeAnalysis.Test/Maintainability/Maintainability/AvoidAssignmentInConditionAnalyzerTest.cs
Philips.CodeAnalysis.Test/Maintainability/Maintainability/AvoidAsyncVoidAnalyzerTest.cs
Philips.CodeAnalysis.Test/Maintainability/Maintainability/AvoidChangingLoopVariablesAnalyzerTest.cs
Philips.CodeAnalysis.Test/Maintainability/Maintainability/AvoidMagicNumbersAnalyzerTest.cs
Philips.CodeAnalysis.Test/Maintainability/Maintainability/AvoidOverrideWithNewKeywordAnalyzerTest.cs
Philips.CodeAnalysis.Test/Maintainability/Maintainability/AvoidTaskResultAnalyzerTest.cs
Philips.CodeAnalysis.Test/Maintainability/Maintainability/AvoidUsingParametersAsTempVariablesAnalyzerTest.cs
Philips.CodeAnalysis.Test/Maintainability/Maintainability/CastCompleteObjectAnalyzerTest.cs
Philips.CodeAnalysis.Test/Maintainability/Maintainability/LogExceptionAnalyzerTest.cs
Philips.CodeAnalysis.Test/Maintainability/Maintainability/LogExceptionAnalyzerTest2.cs
Philips.CodeAnalysis.Test/Maintainability/Maintainability/PassByRefAnalyzerTest.cs
Philips.CodeAnalysis.Test/Maintainability/Maintainability/PassSenderToEventHandlerAnalyzerTest.cs
Philips.CodeAnalysis.Test/Maintainability/Maintainability/ReturnImmutableCollectionsAnalyzerTest.cs
Philips.CodeAnalysis.Test/Maintainability/Maintainability/ThrowInnerExceptionAnalyzerTest.cs
Philips.CodeAnalysis.Test/Maintainability/Naming/AlignFilenameAndClassNameAnalyzerTest.cs
Philips.CodeAnalysis.Test/Maintainability/Readability/LimitConditionComplexityAnalyzerTest2.cs
Philips.CodeAnalysis.Test/Maintainability/RuntimeFailure/LimitPathLengthAnalyzerTest.cs
Philips.CodeAnalysis.Test/Maintainability/RuntimeFailure/NoSpaceInFilenameAnalyzerTest.cs
Philips.CodeAnalysis.Test/Security/AvoidPasswordAnalyzerTest.cs

Fixes some dogfood issues in the Test project

fix: DataTestMethod when using parameters

---

Philips.CodeAnalysis.Common/AdditionalFilesHelper.cs
Philips.CodeAnalysis.Common/AllowedSymbols.cs
Philips.CodeAnalysis.Common/ExceptionsOptions.cs
Philips.CodeAnalysis.Common/SyntaxNodeAction.cs
Philips.CodeAnalysis.Common/TestHelper.cs
Philips.CodeAnalysis.DuplicateCodeAnalyzer/AvoidDuplicateCodeAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/AvoidStaticClassesAnalyzer.cs

chore: fix naming dogfood

---

Philips.CodeAnalysis.Test/Helpers/AssertCodeHelper.cs
Philips.CodeAnalysis.Test/Maintainability/Maintainability/AvoidPrivateKeyPropertyAnalyzerTest.cs
Philips.CodeAnalysis.Test/Maintainability/Maintainability/CallExtensionMethodsAsInstanceMethodsAnalyzerTest.cs
Philips.CodeAnalysis.Test/Moq/MockObjectsMustCallExistingConstructorsAnalyzerTest.cs
Philips.CodeAnalysis.Test/Moq/MockRaiseArgumentsMustMatchEventAnalyzerTest.cs
Philips.CodeAnalysis.Test/MsTest/NoEmptyTestMethodsDiagnosticAnalyzerTest.cs
Philips.CodeAnalysis.Test/MsTest/TestContextAnalyzerTest.cs
Philips.CodeAnalysis.Test/Security/RegexNeedsTimeoutAnalyzerTest.cs
Philips.CodeAnalysis.Test/Verifiers/AssertCodeFixVerifier.cs
Philips.CodeAnalysis.Test/Verifiers/AssertDiagnosticVerifier.cs
Philips.CodeAnalysis.Test/Verifiers/DiagnosticVerifier.Helper.cs

Simplify the code and solve dogfood in one go

test: Change GetMetadataReference to ImmutableArray

---

Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/NoHardCodedPathsAnalyzer.cs
Philips.CodeAnalysis.SecurityAnalyzers/RegexNeedsTimeoutAnalyzer.cs
Philips.CodeAnalysis.Test/Maintainability/Maintainability/NoHardCodedPathsAnalyzerTest.cs
Philips.CodeAnalysis.Test/Security/RegexNeedsTimeoutAnalyzerTest.cs
Philips.CodeAnalysis.Test/Verifiers/AssertCodeFixVerifier.cs
Philips.CodeAnalysis.Test/Verifiers/DiagnosticVerifier.cs

Disabled:
- PH2080: Hardcoded paths
- PH3137: Regex timeout

test: disable some Analyzers for test code

---

Documentation/Diagnostics/PH2032.md
Documentation/Diagnostics/PH2089.md
Documentation/Diagnostics/PH2096.md
Documentation/Diagnostics/PH2097.md
Documentation/Diagnostics/PH2098.md
Documentation/Diagnostics/PH2103.md
Documentation/Diagnostics/PH2105.md
Documentation/Diagnostics/PH2106.md
Documentation/Diagnostics/PH2107.md
Documentation/Diagnostics/PH2108.md
Documentation/Diagnostics/PH2109.md
Documentation/Diagnostics/PH2110.md
Documentation/Diagnostics/PH2114.md
Documentation/Diagnostics/PH2116.md
Documentation/Diagnostics/PH2118.md
Documentation/Diagnostics/PH2125.md
Documentation/Diagnostics/PH2136.md
Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/AvoidArrayListAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/AvoidAssignmentInConditionAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/AvoidAsyncVoidAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/AvoidEmptyStatementBlocksCodeFixProvider.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/AvoidEmptyTypeInitializerAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/AvoidInvocationAsArgumentAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/AvoidPrivateKeyPropertyAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/AvoidUnnecessaryWhereAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Philips.CodeAnalysis.MaintainabilityAnalyzers.md
Philips.CodeAnalysis.Test/Maintainability/Maintainability/AvoidEmptyTypeInitializerAnalyzerTest.cs

Small batch to prevent major rework in case of general findings.

docs: More helplink documentation

---

.github/workflows/changelog.yml

until decision re circumventing branch protection is made.

ci: disable changelog

---

Philips.CodeAnalysis.MaintainabilityAnalyzers/Documentation/DocumentThrownExceptionsAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Documentation/EnableDocumentationCreationAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Documentation/RemoveCommentedCodeAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/AlignOperatorsCountAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/AvoidArrayListAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/AvoidDuplicateStringsAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/AvoidEmptyStatementBlocksAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/AvoidInvocationAsArgumentAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/AvoidMagicNumbersAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/AvoidOverridingWithNewKeywordAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/AvoidThrowingUnexpectedExceptionsAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/AvoidUnnecessaryWhereAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/AvoidUsingParametersAsTempVariablesAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/CastCompleteObjectAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/MergeIfStatementsAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/PassSenderToEventHandlerAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/ReduceCognitiveLoadAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/ReturnImmutableCollectionsAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/SetPropertiesInAnyOrderAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Naming/AlignFilenameAndClassNameAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Naming/NamespaceMatchAssemblyNameAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Readability/AvoidMultipleLambdasOnSingleLineAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Readability/EveryLinqStatementOnSeparateLineAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/Readability/SplitMultiLineConditionOnLogicalOperatorAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/RuntimeFailure/AvoidImplementingFinalizersAnalyzer.cs
Philips.CodeAnalysis.MaintainabilityAnalyzers/RuntimeFailure/UnmanagedObjectsNeedDisposingAnalyzer.cs
Philips.CodeAnalysis.SecurityAnalyzers/RegexNeedsTimeoutAnalyzer.cs
Philips.CodeAnalysis.Test/Verifiers/DiagnosticVerifier.Helper.cs

We'll enable them 1 at a time for actual releases, to ease adoption.

chore: disable all new analyzers

---

.editorconfig
Documentation/Diagnostics/PH2001.md
Documentation/Diagnostics/PH2102.md

We will document our decision to permanently disable [CS1591](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs1591)

docs: 439 enable cs1591

---

Philips.CodeAnalysis.Common/Categories.cs
Philips.CodeAnalysis.MsTestAnalyzers/AssertAreEqualAnalyzer.cs
Philips.CodeAnalysis.MsTestAnalyzers/AssertAreEqualLiteralAnalyzer.cs
Philips.CodeAnalysis.MsTestAnalyzers/AssertAreEqualTypesMatchAnalyzer.cs
Philips.CodeAnalysis.MsTestAnalyzers/AssertFailAnalyzer.cs
Philips.CodeAnalysis.MsTestAnalyzers/AssertIsTrueAnalyzer.cs
Philips.CodeAnalysis.MsTestAnalyzers/AssertIsTrueLiteralAnalyzer.cs
Philips.CodeAnalysis.MsTestAnalyzers/AssertIsTrueParenthesisAnalyzer.cs
Philips.CodeAnalysis.MsTestAnalyzers/AvoidAssertConditionalAccessAnalyzer.cs
Philips.CodeAnalysis.MsTestAnalyzers/AvoidAttributeAnalyzer.cs
Philips.CodeAnalysis.MsTestAnalyzers/AvoidMsFakesAnalyzer.cs
Philips.CodeAnalysis.MsTestAnalyzers/DataTestMethodsHaveDataRowsAnalyzer.cs
Philips.CodeAnalysis.MsTestAnalyzers/ExpectedExceptionAttributeAnalyzer.cs
Philips.CodeAnalysis.MsTestAnalyzers/NoEmptyTestMethodsDiagnosticAnalyzer.cs
Philips.CodeAnalysis.MsTestAnalyzers/TestClassMustBePublicAnalyzer.cs
Philips.CodeAnalysis.MsTestAnalyzers/TestClassPublicMethodShouldBeTestMethodAnalyzer.cs
Philips.CodeAnalysis.MsTestAnalyzers/TestContextAnalyzer.cs
Philips.CodeAnalysis.MsTestAnalyzers/TestHasCategoryAnalyzer.cs
Philips.CodeAnalysis.MsTestAnalyzers/TestHasDescriptionAnalyzer.cs
Philips.CodeAnalysis.MsTestAnalyzers/TestHasTimeoutAnalyzer.cs
Philips.CodeAnalysis.MsTestAnalyzers/TestMethodsMustBeInTestClassAnalyzer.cs
Philips.CodeAnalysis.MsTestAnalyzers/TestMethodsMustBePublicAnalyzer.cs
Philips.CodeAnalysis.MsTestAnalyzers/TestMethodsMustHaveTheCorrectNumberOfArgumentsAnalyzer.cs
Philips.CodeAnalysis.MsTestAnalyzers/TestMethodsShouldHaveUniqueNamesAnalyzer.cs
Philips.CodeAnalysis.MsTestAnalyzers/TestMethodsShouldHaveValidReturnTypesAnalyzer.cs

Updated the Category names to include a "Philips" prefix.
Made a separate category for MsTest.
This solves #493 and solves #473

feat: Change category names

---

Philips.CodeAnalysis.MaintainabilityAnalyzers/Naming/PassByRefAnalyzer.cs

No associated issue, just stumbled upon this while working on another Analyzer. This fix deserves its own PR.

fix: false positive on empty method bodies

---

Documentation/Diagnostics/PH2001.md

Fix 'related analyzers' section

docs: Update PH2001.md

---

Documentation/Diagnostics/PH2121.md
Philips.CodeAnalysis.MaintainabilityAnalyzers/Documentation/DocumentThrownExceptionsAnalyzer.cs
Philips.CodeAnalysis.Test/Maintainability/Documentation/ThrowInformationalExceptionsTest.cs

fix: Ignore NotImplementedException

---

.github/workflows/doc-update.yml

fix: Move environment variables to env section of yml

---

.github/workflows/codeql-analysis.yml
Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/AvoidThreadSleepAnalyzer.cs
Philips.CodeAnalysis.Test/Maintainability/Maintainability/AvoidThreadSleepTest.cs

Made the depth hierarchy flexible, instead of hardcoding a number of `Parent`'s

fix: Flexible hierarchy depth

---

Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/AvoidAssignmentInConditionAnalyzer.cs
Philips.CodeAnalysis.Test/Maintainability/Maintainability/AvoidAssignmentInConditionAnalyzerTest.cs

fix: false positive ph2089 anonymous object initialization mistaken for assignment in condition

---

Philips.CodeAnalysis.Common/AllowedSymbols.cs
Philips.CodeAnalysis.Common/DocumentationHelper.cs
Philips.CodeAnalysis.Common/Inspection/CallTreeIteratorDeepestFirst.cs
Philips.CodeAnalysis.Common/NamespaceResolver.cs

fix: Make AllowedSymbols thread safe

---

Philips.CodeAnalysis.MaintainabilityAnalyzers/Readability/EnforceRegionsRemoveEmptyRegionCodeFixProvider.cs
Philips.CodeAnalysis.Test/Maintainability/Readability/EnforceRegionsRemoveEmptyRegionAnalyzerTest.cs

Sonarqube findings from previous commit.

refactor: sonarqube findings

---

.github/workflows/tagversion.yml

handle single quotes in the titles

ci: fix tagversion.yml to handle apostrophes
