Philips.CodeAnalysis.MaintainabilityAnalyzers/NoNestedStringFormatsAnalyzer.cs, Philips.CodeAnalysis.MaintainabilityAnalyzers/Philips.CodeAnalysis.MaintainabilityAnalyzers.csproj, Philips.CodeAnalysis.Test/NoNestedStringFormatsAnalyzerTest.cs
Prevent crashes in analyzer due to the assumption that Format("{0}") will have at least 1 argument
=> updated nonnestedstringformat analyzer (PR1115)

Philips.CodeAnalysis.DuplicateCodeAnalyzer/Philips.CodeAnalysis.DuplicateCodeAnalyzer.csproj, Philips.CodeAnalysis.MaintainabilityAnalyzers/Philips.CodeAnalysis.MaintainabilityAnalyzers.csproj, Philips.CodeAnalysis.MoqAnalyzers/Philips.CodeAnalysis.MoqAnalyzers.csproj, Philips.CodeAnalysis.MsTestAnalyzers/Philips.CodeAnalysis.MsTestAnalyzers.csproj
such that PrivateAssets is set and the analyzer does not transitively flow to clients' deployments
https://docs.microsoft.com/en-us/dotnet/core/tools/csproj
=> Add developmentDependency flag

Philips.CodeAnalysis.MsTestAnalyzers/AssertAreEqualAnalyzer.cs, Philips.CodeAnalysis.MsTestAnalyzers/AssertMethodCallDiagnosticAnalyzer.cs, Philips.CodeAnalysis.MsTestAnalyzers/Philips.CodeAnalysis.MsTestAnalyzers.csproj, Philips.CodeAnalysis.Test/AssertAreEqualAnalyzerTest.cs, Philips.CodeAnalysis.Test/Verifiers/AssertCodeFixVerifier.cs
=> mayerj add support for default, and handle Assert.AreEqual<string>(x, y)

Philips.CodeAnalysis.Common/Helper.cs, Philips.CodeAnalysis.MsTestAnalyzers/AssertAreEqualAnalyzer.cs, Philips.CodeAnalysis.Test/AssertAreEqualAnalyzerTest.cs
Handle more cases in the <actual> -> <expected> Assert.AreEqual analyzer.  Handle -1, as a constant.
Closes #36
=> Handle -1 and other trivial constants so that the analyzer correctly reports that it should be expected, then actual for Assert.AreEqual

Philips.CodeAnalysis.MaintainabilityAnalyzers/Philips.CodeAnalysis.MaintainabilityAnalyzers.csproj, Philips.CodeAnalysis.MaintainabilityAnalyzers/PreventUnnecessaryRangeChecksAnalyzer.cs, Philips.CodeAnalysis.Test/PreventUnnecessaryRangeChecksAnalyzerTest.cs
This analyzer previous worked with stuff like this:
List<int> list = GetList();
if(list.Count > 0)
{
foreach(int i in list)
{
//do something
}
}
However, it didn't work for the following:
class Foo 
{
public List<int> list = GetList();
}
Foo foo = new Foo();
if(foo.list.Count > 0)
{
foreach(int i in foo.list)
{
//do something
}
}
=> Don't range check nested properties

Philips.CodeAnalysis.Common/AdditionalFilesHelper.cs, Philips.CodeAnalysis.Common/Philips.CodeAnalysis.Common.csproj, Philips.CodeAnalysis.DuplicateCodeAnalyzer/Philips.CodeAnalysis.DuplicateCodeAnalyzer.csproj, Philips.CodeAnalysis.MaintainabilityAnalyzers/AvoidStaticMethodAnalyzer.cs, Philips.CodeAnalysis.MaintainabilityAnalyzers/Philips.CodeAnalysis.MaintainabilityAnalyzers.csproj, Philips.CodeAnalysis.MaintainabilityAnalyzers/PreventUnnecessaryRangeChecksAnalyzer.cs, Philips.CodeAnalysis.MoqAnalyzers/Philips.CodeAnalysis.MoqAnalyzers.csproj, Philips.CodeAnalysis.MsTestAnalyzers/Philips.CodeAnalysis.MsTestAnalyzers.csproj, Philips.CodeAnalysis.Test/AvoidDuplicateCodeTest.cs, Philips.CodeAnalysis.Test/Helpers/DiagnosticVerifier.Helper.cs, Philips.CodeAnalysis.Test/Philips.CodeAnalysis.Test.csproj, Philips.CodeAnalysis.Test/TestHasCategoryTest.cs, README.md
Rollback to older versions of libraries, APIs, and to .netstandard1.3, so as to work with Visual Studio 2017.
https://github.com/WalkerCodeRanger/ExhaustiveMatching/issues/33#issuecomment-673724966
https://docs.microsoft.com/en-us/visualstudio/code-quality/install-fxcop-analyzers?view=vs-2019#fxcopanalyzers-package-versions
=> Support VS2017

Philips.CodeAnalysis.MsTestAnalyzers/Philips.CodeAnalysis.MsTestAnalyzers.csproj, Philips.CodeAnalysis.MsTestAnalyzers/TestHasCategoryAnalyzer.cs, Philips.CodeAnalysis.Test/TestHasCategoryTest.cs
It was changed to look at the literal value in the attribute, which isn't actually what we want.
Go back to looking at the MemberAccessExpressionSyntax.
=> Fix the TestCategory analyzer

Philips.CodeAnalysis.Common/DiagnosticIds.cs, Philips.CodeAnalysis.MaintainabilityAnalyzers/NoHardCodedPathsAnalyzer.cs, Philips.CodeAnalysis.Test/NoHardCodedPathsAnalyzerTest.cs
Reports diagnostics if an absolute path is used, for example: c:\users\Bin\example.xml.
**Files Modified:**
Philips.CodeAnalysis.Common/DiagnosticIds.cs
**Files Added:**
Philips.CodeAnalysis.MaintainabilityAnalyzers/NoHardCodedPathsAnalyzer.cs
Philips.CodeAnalysis.Test/NoHardCodedPathsAnalyzerTest.cs
**Files Removed:**
None
=> Analyzer to check absolute paths

Philips.CodeAnalysis.Common/DiagnosticIds.cs, Philips.CodeAnalysis.MaintainabilityAnalyzers/DontLockNewObjectAnalyzer.cs, Philips.CodeAnalysis.MaintainabilityAnalyzers/OrderPropertyAccessorsAnalyzer.cs, Philips.CodeAnalysis.MaintainabilityAnalyzers/Philips.CodeAnalysis.MaintainabilityAnalyzers.csproj, Philips.CodeAnalysis.MaintainabilityAnalyzers/Philips.CodeAnalysis.MaintainabilityAnalyzers.md, Philips.CodeAnalysis.MsTestAnalyzers/AssertAreEqualAnalyzer.cs, Philips.CodeAnalysis.MsTestAnalyzers/AssertAreEqualLiteralAnalyzer.cs, Philips.CodeAnalysis.MsTestAnalyzers/AssertIsTrueFalseDiagnosticAnalyzer.cs, Philips.CodeAnalysis.MsTestAnalyzers/AssertMethodCallDiagnosticAnalyzer.cs, Philips.CodeAnalysis.MsTestAnalyzers/AvoidAssertConditionalAccessAnalyzer.cs, Philips.CodeAnalysis.Test/AvoidAssertConditionalAccessAnalyzerTest.cs, Philips.CodeAnalysis.Test/DontLockNewObjectAnalyzerTest.cs, Philips.CodeAnalysis.Test/OrderPropertyAccessorsAnalyzerTest.cs, Philips.CodeAnalysis.Test/Verifiers/AssertDiagnosticVerifier.cs
* analyzer for avoiding lock(new object())
* note that an existing analyzer said that the lock needed to be readonly, but that only applied if it was a field
* analyzer for avoiding "set/get" properties (prefer get/set)
* Fixed an oversight which allowed nullable operators in asserts, as long as they weren't directly in the ArgumentSytax
=> Add new analyzers

Philips.CodeAnalysis.MaintainabilityAnalyzers/AvoidTaskResultAnalyzer.cs, Philips.CodeAnalysis.MaintainabilityAnalyzers/Philips.CodeAnalysis.MaintainabilityAnalyzers.csproj, Philips.CodeAnalysis.Test/AvoidTaskResultAnalyzerTest.cs
Fix AvoidTask bug in CodeFixer where "foo.workAsync().Result" erroneously refactored to "await foo.Result" due to span start location
=> AvoidTask CodeFixer bug fix

.editorconfig, Philips.CodeAnalysis.MaintainabilityAnalyzers/CopyrightPresentAnalyzer.cs, Philips.CodeAnalysis.MaintainabilityAnalyzers/Philips.CodeAnalysis.MaintainabilityAnalyzers.csproj, Philips.CodeAnalysis.MaintainabilityAnalyzers/Philips.CodeAnalysis.MaintainabilityAnalyzers.md, Philips.CodeAnalysis.Test/CopyrightPresentAnalyzerTest.cs
And make company name configurable in .editorconfig (see our own .editorconfig)
=> Extend copyright present analyzer with year and company name

Philips.CodeAnalysis.Common/DiagnosticIds.cs, Philips.CodeAnalysis.MsTestAnalyzers/Philips.CodeAnalysis.MsTestAnalyzers.csproj, Philips.CodeAnalysis.MsTestAnalyzers/Philips.CodeAnalysis.MsTestAnalyzers.md, Philips.CodeAnalysis.MsTestAnalyzers/TestMethodsShouldHaveValidReturnTypesAnalyzer.cs, Philips.CodeAnalysis.Test/TestMethodsShouldHaveValidReturnTypesAnalyzerTest.cs
Add an error for returning something  other than void or Task from a testmethod (Task for async, void otherwise)
=> Force testmethods to return void or task only

Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/AvoidStaticMethodAnalyzer.cs, Philips.CodeAnalysis.MaintainabilityAnalyzers/Philips.CodeAnalysis.MaintainabilityAnalyzers.csproj
Add exception for static methods with return type IEnumerable<object[]>, which is the return type for methods used by Dynamic Data.
This fixes #83
=> Add static method exception

.github/workflows/dotnetcore.yml, Philips.CodeAnalysis.MaintainabilityAnalyzers/Philips.CodeAnalysis.MaintainabilityAnalyzers.csproj, Philips.CodeAnalysis.MaintainabilityAnalyzers/RuntimeFailure/DereferenceNullAnalyzer.cs, Philips.CodeAnalysis.Test/DereferenceNullAnalyzerTest.cs
If the statement of interest (where the typecasting occurs) is nested within another statement, the DereferenceNullAnalyzer fails to find the statement. Failure to find the statement results in a null reference exception.
=> Fix argument out of range exception

Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/AvoidPragmaAnalyzer.cs, Philips.CodeAnalysis.Test/Maintainability/Maintainability/AvoidPragmaAnalyzerTest.cs
Sometimes, there is a false positive in assembly level Attribute syntax.
These attributes however, cannot accept a `SuppressMessage`, as `SuppressMessageAttribute` is not allowed on `Attributes`. You also cannot specify a `Target` property pointing to an assembly level Attribute.
The only remediation then, is to use a `#pragma warning disable FP0001`, where PF0001 is the example rule that has the false positive.
However, currently this triggers PH2029. I want to disable PH2029 just for a single line and therefore I used:
`#pragma warning disable PH2029, FP0001` and restore it again right.
However, `AvoidPragmaAnalyzer` doesn't allow itself to be disabled by `#pragma`.
**This leaves me with nowhere to go.**
To break this endless loop, I created this PR.
=> Allow AvoidPragma to be disabled by pragma

Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/NoNestedStringFormatsAnalyzer.cs, Philips.CodeAnalysis.Test/Maintainability/Maintainability/NoNestedStringFormatsAnalyzerTest.cs
After some experimentation around the reported #134 I have found a reproduction scenario. Reworked the issue134 testcases such that it reproduced the false positive.
The root cause in the Analyzer was that _any_ interpolated string was considered a violation. But if used as argument to a method that has 'FormattableString' as its Parameter, the interpolated format is OK. Make an explicit check for this in the Analyzer, searching in the Operation hierarchy for an `IInvocationOperation`, as this might be several levels up the hierarchy..
=> Fix false positive on FormattableString method argument

Philips.CodeAnalysis.MaintainabilityAnalyzers/Documentation/XmlDocumentationCodeFixProvider.cs, Philips.CodeAnalysis.Test/Maintainability/Documentation/XmlDocumentationShouldAddValueAnalyzerTest.cs, Philips.CodeAnalysis.Test/Verifiers/CodeFixVerifier.cs
This solves #154 
Added a check in the CodeFixVerifier to make sure the fixer is fixing the designated diagnostics. This ensures the reported FixableDiagnosticsIds are actually from the associated Analyzer.
There were not many violations, but I feel this is still a good check to keep in.
=> Add check on CodeFixProviders on their designated diagnostics

Philips.CodeAnalysis.MaintainabilityAnalyzers/Philips.CodeAnalysis.MaintainabilityAnalyzers.csproj, Philips.CodeAnalysis.MaintainabilityAnalyzers/RuntimeFailure/DereferenceNullAnalyzer.cs, Philips.CodeAnalysis.Test/Maintainability/RuntimeFailure/DereferenceNullAnalyzerTest.cs
This fixes #156 
Solved various cases where there is a valid null check, but where the Analyzer didn't see them.
=> Fix multiple false positives on 'as' expression

Philips.CodeAnalysis.Common/DiagnosticIds.cs, Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/AvoidInvocationAsArgument.cs, Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/AvoidInvocationAsArgumentCodeFixProvider.cs, Philips.CodeAnalysis.Test/Maintainability/Maintainability/AvoidInvocationAsArgumentTest.cs
New analyzer to extract a local variable. e.g.,
```
Moo(Foo())
```
becomes
```
var resultOfFoo = Foo();
Moo(resultOfFoo)
```
Many variations are accounted for, including constructor initializers, expression bodies, statics, ToString, returns, etc. The Rename Dialog is invoked.
=> Extract Local Variable

Philips.CodeAnalysis.Common/DiagnosticIds.cs, Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/AlignOperatorsCountAnalyzer.cs, Philips.CodeAnalysis.MaintainabilityAnalyzers/OperatorsVisitor.cs, Philips.CodeAnalysis.MaintainabilityAnalyzers/Philips.CodeAnalysis.MaintainabilityAnalyzers.csproj, Philips.CodeAnalysis.MaintainabilityAnalyzers/Philips.CodeAnalysis.MaintainabilityAnalyzers.md, Philips.CodeAnalysis.Test/Maintainability/Maintainability/AlignOperatorsCountAnalyzerTest.cs
Extend the existing Analyzer to count pairs of:
- `>` and `<`
- `>=` and `<=`
- `>>` and `<<`
- `++` and `--`
The compiler will add the compound operators: `+=`, `-=` etc
=> feat: Extend the existing AlignOperatorCountAnalyzer

Philips.CodeAnalysis.Common/DiagnosticIds.cs, Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/AvoidOverridingWithNewKeywordAnalyzer.cs, Philips.CodeAnalysis.MaintainabilityAnalyzers/Philips.CodeAnalysis.MaintainabilityAnalyzers.csproj, Philips.CodeAnalysis.MaintainabilityAnalyzers/Philips.CodeAnalysis.MaintainabilityAnalyzers.md, Philips.CodeAnalysis.Test/Maintainability/Maintainability/AvoidOverrideWithNewKeywordAnalyzerTest.cs
Overriding with the new keyword gives unexpected behavior for the callers of the overridden method or property. It is a code smell.
This checks rule [7@404](https://tics.tiobe.com/viewerCS/index.php?ID=2318&CSTD=Rule) of the Philips C# Coding Standard
=> feat: Introduce AvoidOverridingWithNewKeywordAnalyzer

Philips.CodeAnalysis.Common/DiagnosticIds.cs, Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/AvoidArrayListAnalyzer.cs, Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/AvoidArrayListCodeFixProvider.cs, Philips.CodeAnalysis.MaintainabilityAnalyzers/Philips.CodeAnalysis.MaintainabilityAnalyzers.csproj, Philips.CodeAnalysis.MaintainabilityAnalyzers/Philips.CodeAnalysis.MaintainabilityAnalyzers.md, Philips.CodeAnalysis.Test/Maintainability/Maintainability/AvoidArrayListAnalyzerTest.cs
Usage of Arraylist is discouraged by Microsoft for performance reasons, use List<T> instead.
Includes a crude `CodeFixProvider`
This checks rule [12@106](https://tics.tiobe.com/viewerCS/index.php?ID=2118&CSTD=Rule) of the Philips C# Coding Standard
=> feat: Avoid ArrayList Analyzer

.editorconfig, Philips.CodeAnalysis.MaintainabilityAnalyzers/Naming/NamespaceMatchAssemblyAnalyzer.cs, Philips.CodeAnalysis.MaintainabilityAnalyzers/Naming/PassByRefAnalyzer.cs, Philips.CodeAnalysis.MaintainabilityAnalyzers/Philips.CodeAnalysis.MaintainabilityAnalyzers.csproj, Philips.CodeAnalysis.MaintainabilityAnalyzers/Philips.CodeAnalysis.MaintainabilityAnalyzers.md, Philips.CodeAnalysis.Test/Maintainability/Maintainability/PassByRefAnalyzerTest.cs, Philips.CodeAnalysis.Test/Maintainability/Naming/NamespaceMatchAssemblyAnalyzerTest.cs
Add a new option to .editorconfig for PH2006 called `folder_in_namespace`. When true, the files' sub-folders in the file hierarchy must be included in the namespace.
For example, when true, this is allowed:
`namespace Philips.CodeAnalysis.MaintainabilityAnalyzers.Maintainability`
and this is not:
`namespace Philips.CodeAnalysis.MaintainabilityAnalyzers`
For backwards compatibility, default is false. In this mode, regardless of subfolder's, this is allowed:
`namespace Philips.CodeAnalysis.MaintainabilityAnalyzers`
and this is not:
`namespace Philips.CodeAnalysis.MaintainabilityAnalyzers.Maintainability`
=> feat: enhance PH2006- support folder in namespace

Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/AvoidMagicNumbersAnalyzer.cs, Philips.CodeAnalysis.MaintainabilityAnalyzers/Philips.CodeAnalysis.MaintainabilityAnalyzers.md, Philips.CodeAnalysis.Test/Maintainability/Maintainability/AvoidMagicNumbersAnalyzerTest.cs
Magic number are totally fine to include in enumerations. In fact, this is a great way to give meaning and context to that magic number.
=> fix: Allow magic numbers in enumerations

Philips.CodeAnalysis.Common/DiagnosticIds.cs, Philips.CodeAnalysis.MaintainabilityAnalyzers/Documentation/DocumentThrownExceptionsAnalyzer.cs, Philips.CodeAnalysis.MaintainabilityAnalyzers/Philips.CodeAnalysis.MaintainabilityAnalyzers.csproj, Philips.CodeAnalysis.MaintainabilityAnalyzers/Philips.CodeAnalysis.MaintainabilityAnalyzers.md, Philips.CodeAnalysis.Test/Maintainability/Documentation/DocumentThrownExceptionsAnalyzerTest.cs, Philips.CodeAnalysis.Test/Maintainability/Documentation/ThrowInformationalExceptionsTest.cs
This additional check in the existing `DocumentThrownExceptionsAnalyzer` checks rule [8@108](https://tics.tiobe.com/viewerCS/?ID=111&CSTD=Rule) of the Philips C# Coding Standard
=> feat: Introduce check for informational exceptions

Philips.CodeAnalysis.Common/DiagnosticIds.cs, Philips.CodeAnalysis.MaintainabilityAnalyzers/Documentation/DocumentThrownExceptionsAnalyzer.cs, Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/AvoidThrowingUnexpectedExceptionsAnalyzer.cs, Philips.CodeAnalysis.MaintainabilityAnalyzers/Philips.CodeAnalysis.MaintainabilityAnalyzers.csproj, Philips.CodeAnalysis.MaintainabilityAnalyzers/Philips.CodeAnalysis.MaintainabilityAnalyzers.md, Philips.CodeAnalysis.Test/Maintainability/Documentation/AvoidThrowFromUnexpectedLocationsTest.cs, Philips.CodeAnalysis.Test/Maintainability/Maintainability/AvoidThrowingUnexpectedExceptionsAnalyzerTest.cs
Added a new check to the existing `DocumentThrownExceptionsAnalyzer` which checks rule [8@102](https://tics.tiobe.com/viewerCS/?ID=105&CSTD=Rule) of the Philips C# Coding Standard
=> feat: Intoduce Avoid throwing exceptions from unexpected locations check

Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/ReduceCognitiveLoadAnalyzer.cs, Philips.CodeAnalysis.Test/DuplicateCode/AvoidDuplicateCodeTest.cs, Philips.CodeAnalysis.Test/Maintainability/Maintainability/AvoidStaticClassAnalyzerTest.cs, Philips.CodeAnalysis.Test/Maintainability/Maintainability/NoRegionsInMethodAnalyzerTest.cs, Philips.CodeAnalysis.Test/Maintainability/Maintainability/ReduceCognitiveLoadAnalyzerTest.cs, Philips.CodeAnalysis.Test/Maintainability/Maintainability/WinFormsInitializeComponentMustBeCalledOnceAnalyzerTest.cs, Philips.CodeAnalysis.Test/Maintainability/Readability/AvoidInlineNewAnalyzerTest.cs, Philips.CodeAnalysis.Test/MsTest/AvoidMsFakesAnalyzerTest.cs, Philips.CodeAnalysis.Test/Verifiers/DiagnosticVerifier.cs
The analyzer fails on expression bodies because there is not a block.
=> fix: crash in ReduceCognitiveLoadAnalyzer

Philips.CodeAnalysis.Common/DiagnosticIds.cs, Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/AlignOperatorsCountAnalyzer.cs, Philips.CodeAnalysis.MaintainabilityAnalyzers/OperatorsVisitor.cs, Philips.CodeAnalysis.MaintainabilityAnalyzers/Philips.CodeAnalysis.MaintainabilityAnalyzers.csproj, Philips.CodeAnalysis.MaintainabilityAnalyzers/Philips.CodeAnalysis.MaintainabilityAnalyzers.md, Philips.CodeAnalysis.Test/Maintainability/Maintainability/AlignOperatorsCountAnalyzerTest.cs
This checks rule [7@531](https://csviewer.tiobe.com/#/ruleset/rule?setid=4T_Jr6-VSX6fp6egDIhGow&status=CHECKED,UNCHECKED&tagid=6u27MkXORKaev0VNuWR_SA&ruleid=TCjgzMnETo2yCNKdNzCS0Q) of the Philips C# Coding Standard.
We only check if `+` and `==` align here, as PH2105 checks if `+` and `-` align and the compiler checks if `==` and `!=` align.
=> feat: Add check for + and == operators alignment

Philips.CodeAnalysis.Test/DuplicateCode/AvoidDuplicateCodeTest.cs, Philips.CodeAnalysis.Test/Helpers/DiagnosticVerifier.Helper.cs, Philips.CodeAnalysis.Test/Helpers/TestTextLoader.cs
* Register "AdditionalDocuments" with the project when the project is created, so that the CodeFixers can find these configuration files.
* When the Analyzer creates its compilation context in GetSortedDiagnosticsFromDocuments, get the AdditionalDocuments from the project level, rather than from the Test class. That way, if a CodeFixer modifies the contents of the AdditionalDocuments, when the Analyzer is re-run, it will use the updated configuration files.
=> test: Allow Unit Testing CodeFixers that modify AdditionalDocuments

Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/AvoidArrayListAnalyzer.cs, Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/AvoidArrayListCodeFixProvider.cs, Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/CastCompleteObjectAnalyzer.cs, Philips.CodeAnalysis.Test/DuplicateCode/AvoidDuplicateCodeTest.cs, Philips.CodeAnalysis.Test/Maintainability/Maintainability/AvoidAsyncVoidAnalyzerTest.cs, Philips.CodeAnalysis.Test/Verifiers/CodeFixVerifier.cs
Updated the `CodeFixVerifier` to have a test method already. By default it checks if the `FixAllProvider` is the `BatchFixAllProvider`. Fixed a few test cases that violated this guidelines.
However, the test class can override this check and do custom checks. Please create a follow up PR to implement this for the `AvoidDuplicateCodeTest` class.
=> test: Test coverage for fixers

Philips.CodeAnalysis.MaintainabilityAnalyzers/Philips.CodeAnalysis.MaintainabilityAnalyzers.csproj, Philips.CodeAnalysis.MaintainabilityAnalyzers/Philips.CodeAnalysis.MaintainabilityAnalyzers.md, Philips.CodeAnalysis.MaintainabilityAnalyzers/RuntimeFailure/AvoidAssemblyVersionChange.cs, Philips.CodeAnalysis.Test/Maintainability/Maintainability/EnforceEditorConfigAnalyzerTest.cs, Philips.CodeAnalysis.Test/Maintainability/Maintainability/EnforceEditorConfigAnalyzerTest1.cs, Philips.CodeAnalysis.Test/Maintainability/RuntimeFailure/AvoidAssemblyVersionChangeAnalyzerTest.cs, Philips.CodeAnalysis.Test/Maintainability/RuntimeFailure/AvoidAssemblyVersionChangeAnalyzerTest1.cs, Philips.CodeAnalysis.Test/Maintainability/RuntimeFailure/AvoidAssemblyVersionChangeAnalyzerTest2.cs, Philips.CodeAnalysis.Test/Maintainability/RuntimeFailure/AvoidAssemblyVersionChangeAnalyzerTest3.cs, Philips.CodeAnalysis.Test/Maintainability/RuntimeFailure/TestableAssemblyVersionChangeAnalyzer.cs
I have added test classes for `AvoidAssemblyVersionChangeAnalyzer` and `EnforceEditorConfigAnalyzer`. This will increase our code coverage a bit more.
=> test: Coverage improvement for some Analyzers

Philips.CodeAnalysis.Common/DiagnosticIds.cs, Philips.CodeAnalysis.Common/Helper.cs, Philips.CodeAnalysis.Common/NamespaceIgnoringComparer.cs, Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/ReturnImmutableCollectionsAnalyzer.cs, Philips.CodeAnalysis.MaintainabilityAnalyzers/Philips.CodeAnalysis.MaintainabilityAnalyzers.csproj, Philips.CodeAnalysis.MaintainabilityAnalyzers/Philips.CodeAnalysis.MaintainabilityAnalyzers.md, Philips.CodeAnalysis.Test/Common/HelperTest.cs, Philips.CodeAnalysis.Test/Common/NamespaceIgnoringComparerTest.cs, Philips.CodeAnalysis.Test/Maintainability/Maintainability/ReturnImmutableCollectionsAnalyzerTest.cs
The checks rule [5@119](https://csviewer.tiobe.com/#/ruleset/rule?setid=4T_Jr6-VSX6fp6egDIhGow&status=CHECKED,UNCHECKED&tagid=6u27MkXORKaev0VNuWR_SA&ruleid=R8DUGJzYSfWdIWt3nDk7JQ) of the Philips C# Coding Standard.
=> feat: Return immutable collections

Philips.CodeAnalysis.Test/Helpers/DiagnosticResult.cs, Philips.CodeAnalysis.Test/Maintainability/Documentation/DocumentUnhandledExceptionsAnalyzerTest.cs, Philips.CodeAnalysis.Test/Maintainability/Maintainability/AvoidOverrideWithNewKeywordAnalyzerTest.cs, Philips.CodeAnalysis.Test/Maintainability/Maintainability/NoNestedStringFormatsAnalyzerTest.cs, Philips.CodeAnalysis.Test/Maintainability/Maintainability/PreventUseOfGotoAnalyzerTest.cs, Philips.CodeAnalysis.Test/Maintainability/Readability/AvoidMultipleLambdasOnSingleLineAnalyzerTest.cs, Philips.CodeAnalysis.Test/Maintainability/Readability/PreferNamedTuplesAnalyzerTest.cs, Philips.CodeAnalysis.Test/Maintainability/Readability/PreventUnnecessaryRangeChecksAnalyzerTest.cs, Philips.CodeAnalysis.Test/MsTest/AvoidAttributeAnalyzerTest.cs, Philips.CodeAnalysis.Test/MsTest/TestMethodsMustBeInTestClassAnalyzerTest.cs, Philips.CodeAnalysis.Test/MsTest/TestMethodsMustHaveTheCorrectNumberOfArgumentsAnalyzerTest.cs, Philips.CodeAnalysis.Test/MsTest/TestMethodsShouldHaveUniqueNamesAnalyzerTest.cs, Philips.CodeAnalysis.Test/Verifiers/AssertCodeFixVerifier.cs, Philips.CodeAnalysis.Test/Verifiers/DiagnosticVerifier.cs
In many cases the test code was still calling `VerifyDiagnostics` instead of `VerifySuccessfulCompilation`
The reason was that that `VerifyDiagnostics` still allowed in a public method to have an empty array of `DiagnosticsResult`.
I feel we should force this to not be possible. Hence, I removed that overload and offered a better API to create arrays in the `DiagnosticResultHelper`.
This all should clearly indicate the intend of the test code and improve readability of the tests.
=> chore: Remove VerifyDiagnostic overload with empty array

Philips.CodeAnalysis.MaintainabilityAnalyzers/Documentation/DocumentThrownExceptionsAnalyzer.cs, Philips.CodeAnalysis.Test/Maintainability/Documentation/DocumentThrownExceptionsAnalyzerTest.cs, Philips.CodeAnalysis.Test/Maintainability/Documentation/ThrowInformationalExceptionsTest.cs
Use the existing `Helper.GetFullName` extension method to get the proper type name of the exception.
=> fix: Provide exception type ico Fully Qualified name

Philips.CodeAnalysis.MaintainabilityAnalyzers/Readability/AvoidMultipleLambdasOnSingleLineCodeFixProvider.cs, Philips.CodeAnalysis.Test/Maintainability/Readability/AvoidMultipleLambdasOnSingleLineAnalyzerTest.cs
Restricted the formatting to the new node.
=> fix: Avoid multiple lambdas on single line Analyzer is overformatting

Philips.CodeAnalysis.MaintainabilityAnalyzers/Documentation/XmlDocumentationCodeFixProvider.cs, Philips.CodeAnalysis.Test/Maintainability/Documentation/XmlDocumentationShouldAddValueAnalyzerTest.cs
The issue was already fixed and tested [here](https://github.com/philips-software/roslyn-analyzers/blob/55cde4867947d16cabc2ae9b75be7d6bd6482a8a/Philips.CodeAnalysis.Test/Maintainability/Documentation/XmlDocumentationShouldAddValueAnalyzerTest.cs#L346)
=> chore: Code improvements

Philips.CodeAnalysis.MaintainabilityAnalyzers/Philips.CodeAnalysis.MaintainabilityAnalyzers.md, Philips.CodeAnalysis.MaintainabilityAnalyzers/RuntimeFailure/AvoidImplementingFinalizersAnalyzer.cs, Philips.CodeAnalysis.Test/Maintainability/RuntimeFailure/AvoidImplementingFinalizersAnalyzerTest.cs
This is an extension of PH2130, where we allow calls to `Dispose` methods of the same class.
Any calls to other types are not allowed, as you cannot rely on them still being alive during finalization (as the order is not defined).
In effect, this makes it check also rule [5@114](https://csviewer.tiobe.com/#/ruleset/rule?setid=4T_Jr6-VSX6fp6egDIhGow&status=CHECKED,UNCHECKED&tagid=6u27MkXORKaev0VNuWR_SA&ruleid=yjJN_03cRgqVaitDMYIEMg) of the Philips C# Coding Standard
=> feat: Finalizer allows dispose but no other calls

Philips.CodeAnalysis.Common/DiagnosticIds.cs, Philips.CodeAnalysis.MaintainabilityAnalyzers/Naming/AlignFilenameAndClassNameAnalyzer.cs, Philips.CodeAnalysis.MaintainabilityAnalyzers/Philips.CodeAnalysis.MaintainabilityAnalyzers.csproj, Philips.CodeAnalysis.MaintainabilityAnalyzers/Philips.CodeAnalysis.MaintainabilityAnalyzers.md, Philips.CodeAnalysis.Test/Maintainability/Naming/AlignFilenameAndClassNameAnalyzerTest.cs
This new analyzer checks rule [3@504](https://csviewer.tiobe.com/#/ruleset/rule?setid=4T_Jr6-VSX6fp6egDIhGow&status=CHECKED,UNCHECKED&tagid=6u27MkXORKaev0VNuWR_SA&ruleid=n6-OtgaBSmWcGY7gu_iFGA) of the Philips C# Coding Standard
=> feat: Align filename and class name

Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/AvoidStaticClassesAnalyzer.cs, Philips.CodeAnalysis.MaintainabilityAnalyzers/Readability/SplitMultiLineConditionOnLogicalOperatorAnalyzer.cs, Philips.CodeAnalysis.Test/Maintainability/Readability/SplitMultiLineConditionOnLogicalOperatorAnalyzerTest.cs
The behavior was explicitly coded as such, but not documented nor desired. Hence removed it and adapted the test cases.
=> fix: Remove explicit start check

Philips.CodeAnalysis.MaintainabilityAnalyzers/Documentation/CopyrightPresentAnalyzer.cs, Philips.CodeAnalysis.MsTestAnalyzers/MsTestAttributeDefinitions.cs, Philips.CodeAnalysis.MsTestAnalyzers/TestAttributeDiagnosticAnalyzer.cs, Philips.CodeAnalysis.Test/Maintainability/Documentation/CopyrightPresentAnalyzerTest.cs, Philips.CodeAnalysis.Test/Verifiers/DiagnosticVerifier.cs
This should solve the dog food issues around Copyright.
There were three separate issues:
1. Missing copyright in 2 files
2. Comment was not placed on root Node, but on first token
3. Copyright character gets mangled in some encodings of the source code file
All 3 are fixed in the PR.
=> fix: remaining copyright issues

.github/workflows/dogfood.yml
Restrict the dogfood build to NET 7.0 only, to prevent reporting every finding twice.
=> ci: Run dogfood in net7 only

Philips.CodeAnalysis.Common/DiagnosticIds.cs, Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/SetPropertiesInAnyOrderAnalyzer.cs, Philips.CodeAnalysis.MaintainabilityAnalyzers/Naming/PassByRefAnalyzer.cs, Philips.CodeAnalysis.MaintainabilityAnalyzers/Philips.CodeAnalysis.MaintainabilityAnalyzers.csproj, Philips.CodeAnalysis.MaintainabilityAnalyzers/Philips.CodeAnalysis.MaintainabilityAnalyzers.md, Philips.CodeAnalysis.Test/Maintainability/Maintainability/SetPropertiesInAnyOrderAnalyzerTest.cs
The checks rule [7@601](https://csviewer.tiobe.com/#/ruleset/rule?setid=4T_Jr6-VSX6fp6egDIhGow&status=CHECKED,UNCHECKED&tagid=6u27MkXORKaev0VNuWR_SA&ruleid=XO9vkD5ZTfC01xb4GKhskw) of the Philips C# Coding Standard
=> feat: Set properties in any order

Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/AlignOperatorsCountAnalyzer.cs, Philips.CodeAnalysis.Test/Maintainability/Maintainability/AlignOperatorsCountAnalyzerTest.cs
Only raise PH2125 if there is at least one `+` or `-` operator declared.
=> fix: Prevent false positive

Philips.CodeAnalysis.MaintainabilityAnalyzers/Readability/AvoidInlineNewAnalyzer.cs, Philips.CodeAnalysis.Test/Maintainability/Readability/AvoidInlineNewAnalyzerTest.cs
Allow the following methods:
- ToString()
- ToArray()
- ToList()
- AsSpan()
=> fix: 265 avoid inline new ph2021 exclude tostring

Philips.CodeAnalysis.MaintainabilityAnalyzers/Naming/AlignFilenameAndClassNameAnalyzer.cs, Philips.CodeAnalysis.Test/Maintainability/Naming/AlignFilenameAndClassNameAnalyzerTest.cs, Philips.CodeAnalysis.Test/Maintainability/Naming/NamespaceMatchAssemblyNameAnalyzerTest.cs, Philips.CodeAnalysis.Test/Maintainability/Naming/NamespaceMatchFilePathAnalyzerNoFolderTest.cs
Allow generic classes to be in filenames like: `SingleDiagnosticAnalyzer{TU}.cs`
=> fix: Handle generic classes

Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/AvoidMagicNumbersAnalyzer.cs, Philips.CodeAnalysis.Test/Maintainability/Maintainability/AvoidMagicNumbersAnalyzerTest.cs
I agree that `const` local variables are OK.
But named arguments are not in my opinion, so those are still not allowed.
=> fix: AvoidMagicNumbers too aggressive

.github/workflows/ci.yml, .github/workflows/dogfood.yml, .github/workflows/dotnetcore.yml, .github/workflows/performance.yml, .github/workflows/tagversion.yml, Philips.CodeAnalysis.AnalyzerPerformance/Philips.CodeAnalysis.AnalyzerPerformance.csproj, Philips.CodeAnalysis.Benchmark/Philips.CodeAnalysis.Benchmark.csproj, Philips.CodeAnalysis.Common/Philips.CodeAnalysis.Common.csproj, Philips.CodeAnalysis.DuplicateCodeAnalyzer/Philips.CodeAnalysis.DuplicateCodeAnalyzer.csproj, Philips.CodeAnalysis.MaintainabilityAnalyzers/Philips.CodeAnalysis.MaintainabilityAnalyzers.csproj, Philips.CodeAnalysis.MoqAnalyzers/Philips.CodeAnalysis.MoqAnalyzers.csproj, Philips.CodeAnalysis.MsTestAnalyzers/Philips.CodeAnalysis.MsTestAnalyzers.csproj, Philips.CodeAnalysis.SecurityAnalyzers/Philips.CodeAnalysis.SecurityAnalyzers.csproj
This first step creates the artifacts based on the "next" version (which isn't initialized properly yet) and publishes them as a GitHub artifact for 1 day. This will enable local debugging with the packages as desired. The true versioning isn't setup yet (ie dryrun: false). A subsequent step will publish the artifacts to Nuget for main line (still as prerelease) based on the "files" filter.
=> ci: initial semver

Philips.CodeAnalysis.MsTestAnalyzers/TestClassMustBePublicAnalyzer.cs, Philips.CodeAnalysis.Test/MsTest/TestClassMustBePublicAnalyzerTest.cs
It does not seem necessary to enforce class "staticness" for the test discovery
=> fix: Update TestClassMustBePublicAnalyzer

Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/SetPropertiesInAnyOrderAnalyzer.cs, Philips.CodeAnalysis.Test/Maintainability/Maintainability/SetPropertiesInAnyOrderAnalyzerTest.cs
I guess this fixes #681 
@bcollamore could you please check this is the syntax on which the Analyzer crashes ?
=> fix: PH2134 Support read only arrow properties

Philips.CodeAnalysis.MaintainabilityAnalyzers/Philips.CodeAnalysis.MaintainabilityAnalyzers.csproj
Fixed 2 things:
- Include transient dependencies of package references (See [this](https://stackoverflow.com/questions/17281012/some-dll-from-nuget-packages-are-not-copied-to-bin) SO question)
- Add Mono.Cecile assemblies to nupkg
=> fix: Unable to find Mono.Cecil assemblies

.editorconfig, Philips.CodeAnalysis.Common/AdditionalFilesHelper.cs, Philips.CodeAnalysis.Common/AnalyzerPerformanceRecord.cs, Philips.CodeAnalysis.Common/CodeFixHelper.cs, Philips.CodeAnalysis.Common/DocumentationHelper.cs, Philips.CodeAnalysis.Common/Helper.cs, Philips.CodeAnalysis.Common/MethodPredicates.cs, Philips.CodeAnalysis.Common/ModifiersHelper.cs, Philips.CodeAnalysis.DuplicateCodeAnalyzer/AvoidDuplicateCodeAnalyzer.cs, Philips.CodeAnalysis.MaintainabilityAnalyzers/Cardinality/AvoidVoidReturnAnalyzer.cs, Philips.CodeAnalysis.MaintainabilityAnalyzers/Documentation/XmlDocumentationShouldAddValueAnalyzer.cs, Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/AvoidEmptyStatementBlocksAnalyzer.cs, Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/AvoidInvocationAsArgumentAnalyzer.cs, Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/AvoidInvocationAsArgumentCodeFixProvider.cs, Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/CastCompleteObjectAnalyzer.cs, Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/ReturnImmutableCollectionsAnalyzer.cs, Philips.CodeAnalysis.MaintainabilityAnalyzers/Readability/SplitMultiLineConditionOnLogicalOperatorAnalyzer.cs, Philips.CodeAnalysis.MaintainabilityAnalyzers/RuntimeFailure/AvoidAssemblyGetEntryAssemblyAnalyzer.cs, Philips.CodeAnalysis.MaintainabilityAnalyzers/RuntimeFailure/DereferenceNullAnalyzer.cs, Philips.CodeAnalysis.MsTestAnalyzers/AssertAreEqualAnalyzer.cs, Philips.CodeAnalysis.MsTestAnalyzers/TestHasTimeoutAnalyzer.cs, Philips.CodeAnalysis.Test/Common/AdditionalFilesHelperTest.cs, Philips.CodeAnalysis.Test/Common/HelperTest.cs, Philips.CodeAnalysis.Test/Maintainability/RuntimeFailure/AvoidAssemblyGetEntryAssemblyAnalyzerTest.cs
Fixed 4 SonarCloud bugs
And 2 performance improvements
And some coverage improvements
=> fix: Various small improvements

Documentation/Diagnostics/PH2080.md, Philips.CodeAnalysis.MaintainabilityAnalyzers/Maintainability/NoHardCodedPathsAnalyzer.cs, Philips.CodeAnalysis.Test/Maintainability/Maintainability/NoHardCodedPathsAnalyzerTest.cs
Set the limit to 1000, hard coded, to prevent the analysis taking too much time.
Created #735 to prevent creating long string literals in the first place.
=> fix: Limit the length of strings to inspect 

Documentation/Diagnostics/PH2141.md, Philips.CodeAnalysis.Common/DiagnosticId.cs, Philips.CodeAnalysis.MaintainabilityAnalyzers/LocationRangeModel.cs, Philips.CodeAnalysis.MaintainabilityAnalyzers/Philips.CodeAnalysis.MaintainabilityAnalyzers.csproj, Philips.CodeAnalysis.MaintainabilityAnalyzers/Philips.CodeAnalysis.MaintainabilityAnalyzers.md, Philips.CodeAnalysis.MaintainabilityAnalyzers/Readability/EnforceRegionsAnalyzer.cs, Philips.CodeAnalysis.Test/Maintainability/Maintainability/ProhibitDynamicKeywordAnalyzerTest.cs, Philips.CodeAnalysis.Test/Maintainability/Readability/EnforceRegionsTest.cs, Philips.CodeAnalysis.Test/Moq/MockObjectsMustCallExistingConstructorsAnalyzerTest.cs, Philips.CodeAnalysis.Test/MsTest/AssertAreEqualLiteralAnalyzerTest.cs, Philips.CodeAnalysis.Test/MsTest/AssertFailAnalyzerTest.cs, Philips.CodeAnalysis.Test/MsTest/AssertIsTrueLiteralAnalyzerTest.cs, Philips.CodeAnalysis.Test/MsTest/AvoidAssertConditionalAccessAnalyzerTest.cs, Philips.CodeAnalysis.Test/MsTest/DataTestMethodsHaveDataRowsAnalyzerTest.cs, Philips.CodeAnalysis.Test/MsTest/TestMethodsMustBeInTestClassAnalyzerTest.cs, Philips.CodeAnalysis.Test/MsTest/TestMethodsShouldHaveUniqueNamesAnalyzerTest.cs, Philips.CodeAnalysis.Test/MsTest/TestMethodsShouldHaveValidReturnTypesAnalyzerTest.cs
Empty is defined here, as no `TypeDeclaration` or `MemberDeclaration` inside the region.
Please note that regions inside methods are allowed now.
=> fix: Diagnostic on empty regions

Philips.CodeAnalysis.MaintainabilityAnalyzers/Readability/EnforceRegionsAnalyzer.cs, Philips.CodeAnalysis.Test/Maintainability/Documentation/XmlDocumentationShouldAddValueAnalyzerTest.cs, Philips.CodeAnalysis.Test/Maintainability/Readability/EnforceRegionsTest.cs
Analyzer that scans regions does not work well with nested regions. Gracefully bail out in this scenario.
=> fix: bail on nested regions
